### PR TITLE
More accurate defaults handling

### PR DESCRIPTION
**Pull request by zyuhel**
according to issue #107

### CODE REVIEW

**Comment by felixgirault** [comment]
I would have used a little functional goodness on that one. Something like `array_walk($properties, [$this, 'setDefault']);`
What do you think?

**Comment by zyuhel** [comment]
yes it seems more like other project code. will alter patch now.

**Comment by zyuhel** [comment]
hmm array walk calls function as ($value, $key), we got it ($key,$value). i don't think that more functional notice is good if we need to change api.

**Comment by felixgirault** [comment]
Oops, you're right... The for loop will do :)

**Pull request merged**
